#!/bin/bash
######################################
# ARISE
# https://github.com/spectrasecure/arise
arise_version="1.1.0"
######################################

##############################################################
# Begin main script function
# Don't edit below this line unless you know what you're doing
##############################################################

#save the full path to the source and out dirs
source_dir=$(realpath "$2")
output_dir=$(realpath "$3")

cd "$(dirname $0)"

# Set the site config directories. Don't touch this-- changing the config location is not supported at this time
config="$output_dir/config"
source "$source_dir/config/arise.conf"

# Check if we're running a current version of bash before potentially causing code that won't run properly on ancient bash versions
[ "$BASH_VERSINFO" -lt 5 ] && echo -e 'ERROR: Arise requires Bash version 5 or greater to run. Please install a newer version of Bash or ensure that you are using the newest version installed on your computer.\n\nYour current version of Bash is: '"$BASH_VERSINFO"'\n\nYou can verify the current running version of Bash by running the following command: echo "$BASH_VERSINFO"' && exit 1

# Makes sure that our paths have or don't have a '/' as expected regardless of user input.
## Favicon should have a '/' at the start of the path.
[[ $favicon != '' ]] && [[ ${favicon:0:1} != '/' ]] && favicon='/'"$favicon"
## Base URL should not have a '/' at the end.
[[ ${base_url: -1} == '/' ]] && base_url=${base_url::-1}

# Source functions
for FILE in lib/functions/inline/* ; do [[ $FILE == *.sh ]] && source $FILE ; done
for FILE in lib/functions/subshell/* ; do [[ $FILE == *.sh ]] && source $FILE ; done

# Display our pretty logo no matter what when the program is run :)
arise_logo

# Set default build settings
force_overwrite=true
keep_source=false
arise_build="full"

[[ -z "$arise_build" ]] && { arise_help; exit 1; }
echo

# Make sure "arise_out" is empty and copy the source files over there to work from during the build process.
[[ -d $output_dir ]] && [[ "$force_overwrite" == true ]] && rm -rf $output_dir
mkdir -p $output_dir
[[ -n "$(ls -A $output_dir)" ]] && echo -e 'ERROR: The build output directory "/$output_dir" is not empty. Program aborted to prevent overwrite of existing data.\n\nPlease empty the output directory before running Arise again or run your command with the "-f" flag to overwrite the existing output (dangerous).' && exit 1
cp -r "$source_dir". "$output_dir"
## Set an absolute path for $config
config=$(realpath $config)

# Define a temporary file for a list of all source files for post-build cleanup
removelist="$output_dir/arise-remove-$RANDOM.tmp"
touch $removelist
removelist=$(realpath $removelist)

# Run the build process depending on whatever options have been set
if [[ "$arise_build" == "full" ]] || [[ "$arise_build" == "pages_only" ]]; then
        echo -n "Building pages..."
        build_page_tree $output_dir || { echo "ERROR: An error was encountered while building pages. Aborting build cycle."; exit 1; }
        echo " DONE."
fi

if [[ "$arise_build" == "full" ]] || [[ "$arise_build" == "rss_only" ]]; then
        echo -n "Building RSS feed..."
        build_rss $output_dir/rss.xml || { echo "ERROR: An error was encountered while building the RSS feed. Aborting build cycle."; exit 1; }
        echo " DONE."
fi

if [[ "$arise_build" == "full" ]] || [[ "$arise_build" == "sitemap_only" ]]; then
        echo -n "Building sitemap..."
        build_sitemap $output_dir/sitemap.xml || { echo "ERROR: An error was encountered while building the sitemap. Aborting build cycle."; exit 1; }
        echo " DONE."
fi

if [[ "$keep_source" == false ]]; then
        echo -n "Cleaning up build source files from output..."
        # Remove every page that we built from as part of the build cycle
        while read fname; do
                [[ -f "$fname" ]] && rm "$fname"
        done <$removelist
        # Remove site config templates
        rm "$config/header.html"
        rm "$config/content_header.html"
        rm "$config/footer.html"
        rm "$config/arise.conf"
        echo " DONE."
fi

rm $removelist
echo -e '\nBuild completed! Built artefacts have been generated at:\n'"$(realpath $output_dir)"
